name: Deploy Non-Production

run-name: "${{ github.ref_name }} -> ${{ inputs.environment }}"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select environment
        required: true
        type: choice
        options:
          - PROD
          - TEST
          - UAT

permissions:
  contents: read

jobs:

  run-dev:
    name: PROD Deployment
    if: ${{ inputs.environment == 'PROD' }}
    uses: Test-Organization7144/Test-CI-Templates/.github/workflows/deploy-prod.yml@main
    with:
      release_tag: ${{ github.ref_name }}
      repository: ${{ github.repository }}

  run-test:
    name: TEST Deployment
    if: ${{ inputs.environment == 'TEST' }}
    uses: Test-Organization7144/Test-CI-Templates/.github/workflows/deploy-test.yml@main
    with:
      release_tag: ${{ github.ref_name }}
      repository: ${{ github.repository }}

  run-uat:
    name: UAT Deployment
    if: ${{ inputs.environment == 'UAT' }}
    uses: Test-Organization7144/Test-CI-Templates/.github/workflows/deploy-uat.yml@main
    with:
      release_tag: ${{ github.ref_name }}
      repository: ${{ github.repository }}
